site_name: Selection Manager Documentation
site_url: https://Esenin27.github.io/SelectionManager/

theme:
  name: material
  language: en

markdown_extensions:
  - admonition
  - pymdownx.details

plugins:
  - search
  - glightbox

nav:
  - Intro: intro.md
  - Quick Start: index.md
  - Advanced Settings: advanced-settings.md
  - Selection Collisions: collisions.md
  - Visual Style Settings: visual.md
  - Updates: log.md